spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
  redis:
    host: 47.115.8.44
    port: 6379
    database: 1
    timeout: 3000
    jedis:
      pool:
        max-active: 8
        max-wait: 1
        max-idle: 500
        min-idle: 0
  datasource:
    url: jdbc:mysql://10.26.200.29:3306/forest-dev?characterEncoding=UTF-8&autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: szms
    password: szms@12345
    driver-class-name: com.mysql.cj.jdbc.Driver
    resources:
      add-mappings: true
  mail:
    host: smtp.163.com # 网站发送邮件邮箱服务 host
    port: 465
    username: # 邮箱
    password: # 密码
mybatis-plus:
  mapper-locations: classpath:mapper/**/*Mapper.xml
  global-config:
    # 关闭MP3.0自带的banner
    banner: false
    db-config:
      #主键类型
      id-type: ASSIGN_ID
      # 默认数据库表下划线命名
      table-underline: true
  configuration:
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 返回类型为Map,显示null对应的字段
    call-setters-on-nulls: true
wx:
  open:
    componentAppId: #
    componentSecret: #
    componentToken: #
    componentAesKey: #
  mp:
    configs:
      - appId: xxx #微信公众号消息服务器配置的 appId
        secret: xxx #微信公众号消息服务器配置的 secret
        token: xxx #微信公众号消息服务器配置的 token
        aesKey: xxx #微信公众号消息服务器配置的 aesKey
  miniapp:
    configs:
      - appid: #微信小程序消息服务器配置的 appid
        secret: #微信小程序消息服务器配置的 secret
        token: #微信小程序消息服务器配置的 token
        aesKey: #微信小程序消息服务器配置的 EncodingAESKey
        msgDataFormat: JSON
env: dev
#第三方登录
justauth:
  enabled: true
  type:
    GITLAB:
      client-id: ac02d296205b1e36faa01a86ac511e55fbc875b57f3f093a475119c41f614929
      client-secret: e7aca5dc9115dc6fdc23b59cd04e88bc72c838159897a1cda9938e30215d405b
      redirect-uri: http://10.26.201.17:32241/forest/api/thirdLogin/gitlab/callback
  cache:
    type: default
    prefix: 'NEBULA::THIRD_LOGIN'
    timeout: 1h
third:
  authorize: http://10.26.201.103:9000/oauth/authorize
  accessToken: http://10.26.201.103:9000/oauth/token
  userInfo: http://10.26.201.103:9000/api/v4/user
  loginCallBackUrl: http://10.26.201.17:32240/login?
