spring:
  application:
    name: sz-forest
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
server:
  port: 8099
version: 1.0
resource:
  domain: http://10.26.201.17:32240/static # 网站域名
  file-path: http://10.26.201.17:32240/static # 上传文件前缀域名
  pic-path: ../static # 上传文件存储地址
baidu:
  data:
    site: https://yourdomain.com # 百度搜索绑定网站域名
    token: xxxx
  ai:
    appId: xxx # 百度AI-文字识别 应用 appId
    appKey: xxxx # 百度AI-文字识别 应用 appKey
    secretKey: xxxx # 百度AI-文字识别 应用 secretKey
